import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'

import { SITE_DESCRIPTION, SITE_URL } from '@/constants/site'
import { cn } from '@/lib/utils'
import { Providers } from './providers'

import './globals.css'

const figtree = Figtree({ subsets: ['latin'], variable: '--font-sans' })

const TITLE = 'CountMeIn — online booking for group events'

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: '%s · CountMeIn',
  },
  description: SITE_DESCRIPTION,
  applicationName: 'CountMeIn',
  keywords: [
    'group booking',
    'event booking',
    'class booking',
    'online scheduling',
    'reservation',
    'capacity management',
  ],
  alternates: {
    canonical: '/',
  },
  icons: {
    icon: [{ url: '/logo.svg', type: 'image/svg+xml' }],
  },
  // Note: og:image / twitter:image are generated by app/opengraph-image.tsx
  // (the file-based convention) so the card uses the real logo + Figtree font.
  openGraph: {
    type: 'website',
    siteName: 'CountMeIn',
    url: SITE_URL,
    title: TITLE,
    description: SITE_DESCRIPTION,
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: SITE_DESCRIPTION,
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="bg-background">
      <body className={cn('font-sans', 'antialiased', 'text-foreground', figtree.variable)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
