#!/bin/sh
# Generate Pydantic v2 models from the Zod-rendered OpenAPI document.
# The spec (openapi.yaml) is generated by `bun run generate:openapi` and is
# the single source of truth for the wire; this script only renders it into
# Python. Output is committed; CI verifies freshness. DO NOT EDIT the output.
set -eu

cd "$(dirname "$0")/.."

# Pin formatters explicitly: the tool's default is scheduled to change to
# "builtin", which would silently reformat the committed output on upgrade.
uv run datamodel-codegen \
  --input openapi.yaml \
  --input-file-type openapi \
  --formatters black isort \
  --output api/_lib/countmein/contracts/models_gen.py \
  --output-model-type pydantic_v2.BaseModel \
  --use-annotated \
  --field-constraints \
  --use-standard-collections \
  --use-union-operator \
  --target-python-version 3.12 \
  --enum-field-as-literal all \
  --use-schema-description \
  --disable-timestamp \
  --strict-nullable
