/**
 * Generate Go translation dictionaries from `packages/translations`.
 *
 * The Go module cannot `//go:embed` files outside its own tree, and the
 * Go API only needs two slices of the full corpus:
 *   - the `ApiErrors` section of `messages/*.json` (route error copy)
 *   - all of `notifications/*.json` (Telegram bot copy)
 *
 * This script reads the source-of-truth JSON, extracts those slices, and
 * writes a single Go file (`internal/i18n/translations_gen.go`) with the
 * data compiled directly into `map[string]…` literals — no runtime JSON
 * parsing, no embedded copies, no drift. Run via `bun run generate:i18n`.
 *
 * The generated file is committed to the repo (so Vercel builds need no
 * pre-step) and CI verifies it is up to date with `git diff --exit-code`.
 */
import { execSync } from 'node:child_process'
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const rootDir = join(__dirname, '..', '..', '..')
const translationsDir = join(rootDir, 'packages', 'translations')
const messagesDir = join(translationsDir, 'messages')
const notificationsDir = join(translationsDir, 'notifications')
const targetFile = join(__dirname, '..', 'internal', 'i18n', 'translations_gen.go')

/** Escape a string as a Go double-quoted string literal. */
function goString(str: string): string {
  return JSON.stringify(str)
}

function generate(): void {
  const locales = readdirSync(messagesDir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace('.json', ''))
    .sort()

  const apiErrorsByLocale: Record<string, Record<string, string>> = {}
  const notificationsByLocale: Record<
    string,
    { top: Record<string, string>; sections: Record<string, Record<string, string>> }
  > = {}

  for (const locale of locales) {
    // 1. Extract only ApiErrors from messages.
    const msgPath = join(messagesDir, `${locale}.json`)
    const msgContent = JSON.parse(readFileSync(msgPath, 'utf8')) as Record<string, unknown>
    const apiErrors = (msgContent.ApiErrors ?? {}) as Record<string, unknown>
    const errMap: Record<string, string> = {}
    for (const [key, val] of Object.entries(apiErrors)) {
      if (typeof val === 'string') {
        errMap[key] = val
      }
    }
    apiErrorsByLocale[locale] = errMap

    // 2. Extract notifications (top-level strings + nested sections).
    const notifPath = join(notificationsDir, `${locale}.json`)
    const notifContent = JSON.parse(readFileSync(notifPath, 'utf8')) as Record<string, unknown>
    const topMap: Record<string, string> = {}
    const sectionsMap: Record<string, Record<string, string>> = {}

    for (const [section, val] of Object.entries(notifContent)) {
      if (typeof val === 'string') {
        topMap[section] = val
      } else if (typeof val === 'object' && val !== null) {
        const flat: Record<string, string> = {}
        for (const [k, s] of Object.entries(val as Record<string, unknown>)) {
          if (typeof s === 'string') {
            flat[k] = s
          }
        }
        sectionsMap[section] = flat
      }
    }
    notificationsByLocale[locale] = { top: topMap, sections: sectionsMap }
  }

  // Generate Go source.
  let code = `// Code generated by scripts/generate-i18n-go.ts; DO NOT EDIT.
package i18n

func init() {
\tapiErrors = genAPIErrors
\tnotifications = genNotifications
}

var genAPIErrors = map[string]map[string]string{
`

  for (const locale of locales) {
    code += `\t${goString(locale)}: {\n`
    const errMap = apiErrorsByLocale[locale]!
    const keys = Object.keys(errMap).sort()
    for (const k of keys) {
      code += `\t\t${goString(k)}: ${goString(errMap[k]!)},\n`
    }
    code += '\t},\n'
  }
  code += '}\n\n'

  code += 'var genNotifications = map[string]notifDict{\n'
  for (const locale of locales) {
    const dict = notificationsByLocale[locale]!
    code += `\t${goString(locale)}: {\n`
    code += '\t\ttop: map[string]string{\n'
    for (const k of Object.keys(dict.top).sort()) {
      code += `\t\t\t${goString(k)}: ${goString(dict.top[k]!)},\n`
    }
    code += '\t\t},\n'
    code += '\t\tsections: map[string]map[string]string{\n'
    for (const sec of Object.keys(dict.sections).sort()) {
      code += `\t\t\t${goString(sec)}: {\n`
      const flat = dict.sections[sec]!
      for (const k of Object.keys(flat).sort()) {
        code += `\t\t\t\t${goString(k)}: ${goString(flat[k]!)},\n`
      }
      code += '\t\t\t},\n'
    }
    code += '\t\t},\n'
    code += '\t},\n'
  }
  code += '}\n'

  writeFileSync(targetFile, code, 'utf8')
  try {
    execSync(`gofmt -w "${targetFile}"`, { stdio: 'inherit' })
  } catch {
    // If gofmt is unavailable in the current environment, leave the file as-is.
  }
  console.log(`Generated Go translations at ${targetFile}`)
}

generate()
