"""The ORM models mirror the migrated schema: no drift.

Builds a scratch database from the Alembic migrations (0001 baseline),
then runs `alembic check` against it — any model/metadata change that
would generate upgrade ops fails here instead of surfacing as a
runtime SQL error or a silently skipped migration.

Also pins the Phase 2 relationship contract (lazy="raise" everywhere,
passive_deletes on the one-to-many sides the DB cascades/restricts)
and the Python-side id defaults (uuidv7/nanoid fill in on flush —
no DB default exists for these columns).

Requires POSTGRES_URL — skipped locally without it, failed in CI (the
shared rule in tests_py/_env.py). The scratch database is dropped
after the run so repeated runs never see a stale schema.
"""

from __future__ import annotations

from pathlib import Path

import pytest

# Every test needs the live Postgres (scratch database + autogenerate
# comparison) — the whole module is integration.
pytestmark = pytest.mark.integration


def require_postgres() -> str:
    from _env import require_postgres as _require

    return _require()


def _web_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _alembic_config(url: str):
    """Alembic Config pointing at url — the same wiring conftest's
    _migrate uses (ini + script_location + explicit sqlalchemy.url so
    env.py never falls back to whatever .env points at)."""
    from alembic.config import Config as AlembicConfig

    web_root = _web_root()
    cfg = AlembicConfig(str(web_root / "alembic.ini"))
    cfg.set_main_option("script_location", str(web_root / "alembic"))
    cfg.set_main_option("sqlalchemy.url", url)
    return cfg


def test_models_match_migrated_schema():
    """alembic check against a scratch DB migrated to head: no diffs.

    Sync (not async): alembic's env.py drives migrations via
    asyncio.run(), which cannot run inside the event loop
    pytest-asyncio (auto mode) puts async tests in.
    """
    import psycopg
    from conftest import _replace_dbname

    from alembic import command as alembic_command

    base_pg = require_postgres()
    dbname = "countmein_test_models_drift"
    admin_url = _replace_dbname(base_pg, "postgres")
    with psycopg.connect(admin_url, autocommit=True) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{dbname}" WITH (FORCE)')
        conn.execute(f'CREATE DATABASE "{dbname}"')
    try:
        url = _replace_dbname(base_pg, dbname)
        alembic_command.upgrade(_alembic_config(url), "head")
        # Raises AutogenerateDiffsDetected on any model/schema drift;
        # prints "No new upgrade operations detected." when clean.
        alembic_command.check(_alembic_config(url))
    finally:
        with psycopg.connect(admin_url, autocommit=True) as conn:
            conn.execute(f'DROP DATABASE IF EXISTS "{dbname}" WITH (FORCE)')


def test_relationship_loading_contract():
    """lazy="raise" on every relationship (no silent async
    MissingGreenlet); passive_deletes on the one-to-many sides so
    session.delete() lets the DB cascade/restrict instead of
    SELECT-then-nullifying NOT NULL FKs."""
    from countmein.models import Booking, Organizer, Service, TimeSlot

    one_to_many = [
        (Organizer, "services"),
        (Service, "time_slots"),
        (TimeSlot, "bookings"),
    ]
    many_to_one = [
        (Service, "organizer"),
        (TimeSlot, "service"),
        (Booking, "time_slot"),
    ]
    for cls, name in one_to_many + many_to_one:
        assert cls.__mapper__.relationships[name].lazy == "raise", (
            f"{cls.__name__}.{name}: lazy must be 'raise'"
        )
    for cls, name in one_to_many:
        assert cls.__mapper__.relationships[name].passive_deletes is True, (
            f"{cls.__name__}.{name}: passive_deletes must be True"
        )


def test_id_defaults_fill_python_side():
    """The id columns have no DB default (Drizzle's $defaultFn ran
    JS-side): the ORM column defaults generate uuidv7/nanoid ids so
    repositories can build entities without explicit ids."""
    import re

    from countmein.db.shared import new_id, new_service_id
    from countmein.models import Booking, Organizer, Service, TimeSlot

    # NOTE: assert on __wrapped__ — SQLAlchemy wraps a plain-function
    # default in its own callable (schema.py), so `default.arg` is the
    # wrapper, not the original function object (`is new_id` fails).
    assert Organizer.__table__.c.id.default is not None
    assert Organizer.__table__.c.id.default.arg.__wrapped__ is new_id
    assert TimeSlot.__table__.c.id.default is not None
    assert TimeSlot.__table__.c.id.default.arg.__wrapped__ is new_id
    assert Booking.__table__.c.id.default is not None
    assert Booking.__table__.c.id.default.arg.__wrapped__ is new_id
    assert Service.__table__.c.id.default is not None
    assert Service.__table__.c.id.default.arg.__wrapped__ is new_service_id

    assert re.fullmatch(
        r"[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}",
        str(Organizer.__table__.c.id.default.arg(None)),
    )
    assert len(str(Service.__table__.c.id.default.arg(None))) == 21
