# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from typing import Annotated, Any, Dict, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class AuthTicketResponse(BaseModel):
    ticket: Annotated[str, Field(max_length=200, min_length=20)]
    organizerExists: bool


type Contact = Annotated[str, Field(max_length=300, min_length=1)]


class ErrorBody(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    error: str
    code: str | None = None
    seatsLeft: Annotated[
        int | None, Field(ge=-9007199254740991, le=9007199254740991)
    ] = None
    maxSeats: Annotated[
        int | None, Field(ge=-9007199254740991, le=9007199254740991)
    ] = None


class ImageUploadTarget(BaseModel):
    uploadUrl: AnyUrl
    publicUrl: AnyUrl
    expiresAt: str


class InvalidIssuesBody(BaseModel):
    error: str
    issues: dict[str, list[str]]


type Location = Annotated[str, Field(max_length=300, min_length=1)]


class LookupBookingsInput(BaseModel):
    guestTicket: Annotated[str, Field(max_length=200, min_length=20)]


type OptionLabel = Annotated[str, Field(max_length=100, min_length=1)]


type OptionsList = Annotated[list[OptionLabel], Field(max_length=50, min_length=1)]


type OrganizerDescription = Annotated[str, Field(max_length=4000)]


type PriceText = Annotated[str, Field(max_length=50, min_length=1)]


type ServiceDescription = Annotated[str, Field(max_length=2000)]


class UpdateOrganizerLanguageInput(BaseModel):
    language: Literal['en', 'de', 'es', 'fr', 'pt', 'ru', 'ar', 'ja']


class UpdateServiceInput(BaseModel):
    title: Annotated[str | None, Field(max_length=100, min_length=1)] = None
    description: ServiceDescription | None = None
    location: Location | None = None
    contact: Contact | None = None
    defaultPrice: Annotated[str | None, Field(max_length=50, min_length=1)] = None
    defaultCapacity: Annotated[int | None, Field(ge=1, le=100000)] = None
    defaultDurationMinutes: Annotated[int | None, Field(ge=1, le=1440)] = None
    maxSeatsPerBooking: Annotated[int | None, Field(ge=1, le=1000)] = None
    options: OptionsList | None = None
    optionsSelectMode: Literal['single', 'multi'] | None = None
    photoUrl: AnyUrl | None = None


class UpdateTimeSlotInput(BaseModel):
    startsAt: Annotated[
        AwareDatetime | int | None,
        Field(description='Date-only strings are rejected with 400.'),
    ] = None
    durationMinutes: Annotated[int | None, Field(ge=1, le=1440)] = None
    capacity: Annotated[int | None, Field(ge=1, le=100000)] = None
    price: PriceText | None = None


class ValidationErrors(BaseModel):
    formErrors: list[str]
    fieldErrors: dict[str, list[str]]


class AuthTicketPayload(BaseModel):
    messenger: Literal['telegram']
    messengerId: Annotated[str, Field(max_length=100, min_length=1)]
    displayName: str
    photoUrl: AnyUrl | None = None
    messengerLogin: str | None = None
    purpose: Literal['guest', 'organizer']


class BookingCancelledJob(BaseModel):
    bookingId: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    cancelledBy: Literal['guest', 'organizer']
    outboxId: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]


class BookingCreatedJob(BaseModel):
    bookingId: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    recipient: Literal['organizer', 'guest']
    outboxId: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]


class BookingRecord(BaseModel):
    id: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    timeSlotId: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    status: Literal['confirmed', 'cancelled']
    seats: Annotated[int, Field(ge=1, le=1000)]
    guestName: Annotated[str, Field(max_length=100, min_length=1)]
    guestMessenger: Literal['telegram']
    guestMessengerId: str
    guestMessengerLogin: str | None
    selectedOptions: list[str] | None
    createdAt: str


class CancelBookingByOrganizerInput(BaseModel):
    bookingId: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]


class CancelBookingByTokenInput(BaseModel):
    manageToken: Annotated[str, Field(max_length=200, min_length=10)]


class CreateAvatarUploadInput(BaseModel):
    contentType: Literal['image/jpeg', 'image/png', 'image/webp']
    size: Annotated[int, Field(ge=1, le=1048576)]


class CreateBookingInput(BaseModel):
    serviceId: Annotated[str, Field(pattern='^[A-Za-z0-9_-]{6,32}$')]
    timeSlotId: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    seats: Annotated[int, Field(ge=1, le=1000)]
    guestName: Annotated[str, Field(max_length=100, min_length=1)]
    guestTicket: Annotated[str, Field(max_length=200, min_length=20)]
    selectedOptions: Annotated[list[OptionLabel] | None, Field(max_length=50)] = None
    guestLocale: Literal['en', 'de', 'es', 'fr', 'pt', 'ru', 'ar', 'ja'] = 'en'


class CreateServiceInput(BaseModel):
    title: Annotated[str, Field(max_length=100, min_length=1)]
    description: Annotated[str | None, Field(max_length=2000)] = None
    location: Annotated[str | None, Field(max_length=300, min_length=1)] = None
    contact: Annotated[str | None, Field(max_length=300, min_length=1)] = None
    defaultPrice: Annotated[str, Field(max_length=50, min_length=1)]
    defaultCapacity: Annotated[int, Field(ge=1, le=100000)]
    defaultDurationMinutes: Annotated[int, Field(ge=1, le=1440)]
    maxSeatsPerBooking: Annotated[int, Field(ge=1, le=1000)]
    options: Annotated[list[OptionLabel] | None, Field(max_length=50, min_length=1)] = (
        None
    )
    optionsSelectMode: Literal['single', 'multi'] | None = None
    photoUrl: AnyUrl | None = None


class CreateServicePhotoUploadInput(BaseModel):
    contentType: Literal['image/jpeg', 'image/png', 'image/webp']
    size: Annotated[int, Field(ge=1, le=2097152)]


class CreateTimeSlotInput(BaseModel):
    serviceId: Annotated[str, Field(pattern='^[A-Za-z0-9_-]{6,32}$')]
    startsAt: Annotated[
        AwareDatetime | int,
        Field(description='Date-only strings are rejected with 400.'),
    ]
    durationMinutes: Annotated[int, Field(ge=1, le=1440)]
    capacity: Annotated[int, Field(ge=1, le=100000)]
    price: Annotated[str | None, Field(max_length=50, min_length=1)] = None


class DeletedServiceEnvelope(BaseModel):
    id: Annotated[str, Field(pattern='^[A-Za-z0-9_-]{6,32}$')]


class DeletedSlotEnvelope(BaseModel):
    id: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]


class GuestTicketResponse(BaseModel):
    ticket: Annotated[str, Field(max_length=200, min_length=20)]
    messenger: Literal['telegram']
    messengerId: Annotated[str, Field(max_length=100, min_length=1)]
    displayName: str


class InvalidBody(BaseModel):
    error: str
    details: ValidationErrors


class LoginLinkPayload(BaseModel):
    organizerId: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    next: Annotated[str, Field(pattern='^\\/.*')]


class OrganizerProfile(BaseModel):
    id: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    slug: Annotated[
        str, Field(max_length=40, min_length=4, pattern='^[a-z0-9]+(?:-[a-z0-9]+)*$')
    ]
    name: Annotated[str, Field(max_length=100, min_length=1)]
    messenger: Literal['telegram']
    messengerId: str
    timezone: str
    description: str | None
    photoUrl: str | None
    location: str | None
    contact: str | None
    language: Literal['en', 'de', 'es', 'fr', 'pt', 'ru', 'ar', 'ja']
    createdAt: str
    isDemo: bool


class PublicOrganizer(BaseModel):
    id: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    slug: Annotated[
        str, Field(max_length=40, min_length=4, pattern='^[a-z0-9]+(?:-[a-z0-9]+)*$')
    ]
    name: Annotated[str, Field(max_length=100, min_length=1)]
    timezone: str
    description: str | None
    photoUrl: str | None
    location: str | None
    contact: str | None
    isDemo: bool


class RegisteredOrganizer(BaseModel):
    id: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    slug: Annotated[
        str, Field(max_length=40, min_length=4, pattern='^[a-z0-9]+(?:-[a-z0-9]+)*$')
    ]


class ServiceRecord(BaseModel):
    id: Annotated[str, Field(pattern='^[A-Za-z0-9_-]{6,32}$')]
    organizerId: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    title: Annotated[str, Field(max_length=100, min_length=1)]
    description: str | None
    photoUrl: str | None
    location: str | None
    contact: str | None
    defaultPrice: Annotated[str, Field(max_length=50, min_length=1)]
    defaultCapacity: Annotated[int, Field(ge=1, le=100000)]
    defaultDurationMinutes: Annotated[int, Field(ge=1, le=1440)]
    maxSeatsPerBooking: Annotated[int, Field(ge=1, le=1000)]
    options: list[str] | None
    optionsSelectMode: Literal['single', 'multi'] | None
    createdAt: str


class ServicesEnvelope(BaseModel):
    services: list[ServiceRecord]


class TelegramWidgetPayload(BaseModel):
    id: Annotated[int, Field(ge=1, le=9007199254740991)]
    first_name: Annotated[str, Field(max_length=256, min_length=1)]
    last_name: Annotated[str | None, Field(max_length=256)] = None
    username: Annotated[str | None, Field(max_length=256)] = None
    photo_url: AnyUrl | None = None
    auth_date: Annotated[int, Field(ge=1, le=4102444800)]
    hash: Annotated[str, Field(max_length=64, min_length=64)]


class TimeSlotRecord(BaseModel):
    id: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    serviceId: Annotated[str, Field(pattern='^[A-Za-z0-9_-]{6,32}$')]
    startsAt: str
    durationMinutes: Annotated[int, Field(ge=1, le=1440)]
    capacity: Annotated[int, Field(ge=1, le=100000)]
    bookedCount: Annotated[int, Field(ge=0, le=9007199254740991)]
    price: str | None
    createdAt: str


class UpdateOrganizerProfileInput(BaseModel):
    name: Annotated[str | None, Field(max_length=100, min_length=1)] = None
    slug: Annotated[
        str | None,
        Field(max_length=40, min_length=4, pattern='^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    ] = None
    timezone: str | None = None
    description: OrganizerDescription | None = None
    location: Location | None = None
    contact: Contact | None = None
    photoUrl: AnyUrl | None = None


class BookingEnvelope(BaseModel):
    booking: BookingRecord


class GuestBooking(BaseModel):
    id: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    status: Literal['confirmed', 'cancelled']
    seats: Annotated[int, Field(ge=1, le=1000)]
    guestName: Annotated[str, Field(max_length=100, min_length=1)]
    selectedOptions: list[str] | None
    createdAt: str
    manageToken: Annotated[str, Field(max_length=200, min_length=10)]
    canCancel: bool
    slot: TimeSlotRecord
    service: ServiceRecord
    organizer: PublicOrganizer


class GuestBookingEnvelope(BaseModel):
    booking: GuestBooking


class GuestBookingsEnvelope(BaseModel):
    bookings: list[GuestBooking]


class OrganizerEnvelope(BaseModel):
    organizer: OrganizerProfile


class RegisterOrganizerInput(BaseModel):
    ticket: Annotated[str, Field(max_length=200, min_length=20)]
    slug: Annotated[
        str, Field(max_length=40, min_length=4, pattern='^[a-z0-9]+(?:-[a-z0-9]+)*$')
    ]
    name: Annotated[str, Field(max_length=100, min_length=1)]
    timezone: str
    contact: Annotated[str | None, Field(max_length=300, min_length=1)] = None
    language: Literal['en', 'de', 'es', 'fr', 'pt', 'ru', 'ar', 'ja'] = 'en'


class Registered(BaseModel):
    organizer: RegisteredOrganizer


class ServiceEnvelope(BaseModel):
    service: ServiceRecord


class SlotEnvelope(BaseModel):
    slot: TimeSlotRecord


class SlotsEnvelope(BaseModel):
    slots: list[TimeSlotRecord]
