# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from typing import Annotated, Any, Dict, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AppLocale(RootModel[Literal['en', 'de', 'es', 'fr', 'pt', 'ru', 'ar', 'ja']]):
    root: Literal['en', 'de', 'es', 'fr', 'pt', 'ru', 'ar', 'ja']


class AuthTicket(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=20)]


class AuthTicketResponse(BaseModel):
    ticket: AuthTicket
    organizerExists: bool


class AvatarUploadSize(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=1048576)]


class BookingStatus(RootModel[Literal['confirmed', 'cancelled']]):
    root: Literal['confirmed', 'cancelled']


class CancelActor(RootModel[Literal['guest', 'organizer']]):
    root: Literal['guest', 'organizer']


class Capacity(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=100000)]


class Contact(RootModel[str]):
    root: Annotated[str, Field(max_length=300, min_length=1)]


class DisplayName(RootModel[str]):
    root: Annotated[str, Field(max_length=100, min_length=1)]


class DurationMinutes(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=1440)]


class ErrorBody(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    error: str
    code: str | None = None
    seatsLeft: Annotated[
        int | None, Field(ge=-9007199254740991, le=9007199254740991)
    ] = None
    maxSeats: Annotated[
        int | None, Field(ge=-9007199254740991, le=9007199254740991)
    ] = None


class ImageContentType(RootModel[Literal['image/jpeg', 'image/png', 'image/webp']]):
    root: Literal['image/jpeg', 'image/png', 'image/webp']


class ImageUploadTarget(BaseModel):
    uploadUrl: AnyUrl
    publicUrl: AnyUrl
    expiresAt: str


class InvalidIssuesBody(BaseModel):
    error: str
    issues: dict[str, list[str]]


class Location(RootModel[str]):
    root: Annotated[str, Field(max_length=300, min_length=1)]


class LookupBookingsInput(BaseModel):
    guestTicket: AuthTicket


class ManageToken(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=10)]


class MaxSeatsPerBooking(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=1000)]


class Messenger(RootModel[Literal['telegram']]):
    root: Literal['telegram']


class MessengerID(RootModel[str]):
    root: Annotated[str, Field(max_length=100, min_length=1)]


class NotificationRecipient(RootModel[Literal['organizer', 'guest']]):
    root: Literal['organizer', 'guest']


class OptionLabel(RootModel[str]):
    root: Annotated[str, Field(max_length=100, min_length=1)]


class OptionsList(RootModel[list[OptionLabel]]):
    root: Annotated[list[OptionLabel], Field(max_length=50, min_length=1)]


class OptionsSelectMode(RootModel[Literal['single', 'multi']]):
    root: Literal['single', 'multi']


class OrganizerDescription(RootModel[str]):
    root: Annotated[str, Field(max_length=4000)]


class PriceText(RootModel[str]):
    root: Annotated[str, Field(max_length=50, min_length=1)]


class Seats(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=1000)]


class SelectedOptions(RootModel[list[OptionLabel]]):
    root: Annotated[list[OptionLabel], Field(max_length=50)]


class ServiceDescription(RootModel[str]):
    root: Annotated[str, Field(max_length=2000)]


class ServiceID(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Za-z0-9_-]{6,32}$')]


class ServicePhotoUploadSize(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=2097152)]


class SlotStartsAt(RootModel[AwareDatetime | int]):
    root: Annotated[
        AwareDatetime | int,
        Field(description='Date-only strings are rejected with 400.'),
    ]


class SlugShape(RootModel[str]):
    root: Annotated[
        str, Field(max_length=40, min_length=4, pattern='^[a-z0-9]+(?:-[a-z0-9]+)*$')
    ]


class TelegramAuthDate(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=4102444800)]


class TelegramHash(RootModel[str]):
    root: Annotated[str, Field(max_length=64, min_length=64)]


class TelegramName(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class TelegramOptionalName(RootModel[str]):
    root: Annotated[str, Field(max_length=256)]


class TelegramUserID(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=9007199254740991)]


class Timezone(RootModel[str]):
    root: str


class URL(RootModel[AnyUrl]):
    root: AnyUrl


class UUIDModel(RootModel[UUID]):
    root: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]


class UpdateOrganizerLanguageInput(BaseModel):
    language: AppLocale


class UpdateServiceInput(BaseModel):
    title: DisplayName | None = None
    description: ServiceDescription | None = None
    location: Location | None = None
    contact: Contact | None = None
    defaultPrice: PriceText | None = None
    defaultCapacity: Capacity | None = None
    defaultDurationMinutes: DurationMinutes | None = None
    maxSeatsPerBooking: MaxSeatsPerBooking | None = None
    options: OptionsList | None = None
    optionsSelectMode: OptionsSelectMode | None = None
    photoUrl: URL | None = None


class UpdateTimeSlotInput(BaseModel):
    startsAt: SlotStartsAt | None = None
    durationMinutes: DurationMinutes | None = None
    capacity: Capacity | None = None
    price: PriceText | None = None


class ValidationErrors(BaseModel):
    formErrors: list[str]
    fieldErrors: dict[str, list[str]]


class AuthTicketPayload(BaseModel):
    messenger: Messenger
    messengerId: MessengerID
    displayName: str
    photoUrl: AnyUrl | None = None
    messengerLogin: str | None = None
    purpose: Literal['guest', 'organizer']


class BookingCancelledJob(BaseModel):
    bookingId: UUIDModel
    cancelledBy: CancelActor
    outboxId: UUIDModel


class BookingCreatedJob(BaseModel):
    bookingId: UUIDModel
    recipient: NotificationRecipient
    outboxId: UUIDModel


class BookingRecord(BaseModel):
    id: UUIDModel
    timeSlotId: UUIDModel
    status: BookingStatus
    seats: Seats
    guestName: DisplayName
    guestMessenger: Messenger
    guestMessengerId: str
    guestMessengerLogin: str | None
    selectedOptions: list[str] | None
    createdAt: str


class CancelBookingByOrganizerInput(BaseModel):
    bookingId: UUIDModel


class CancelBookingByTokenInput(BaseModel):
    manageToken: ManageToken


class CreateAvatarUploadInput(BaseModel):
    contentType: ImageContentType
    size: AvatarUploadSize


class CreateBookingInput(BaseModel):
    serviceId: ServiceID
    timeSlotId: UUIDModel
    seats: Seats
    guestName: DisplayName
    guestTicket: AuthTicket
    selectedOptions: SelectedOptions | None = None
    guestLocale: Annotated[AppLocale, Field(validate_default=True)] = 'en'


class CreateServiceInput(BaseModel):
    title: DisplayName
    description: ServiceDescription | None = None
    location: Location | None = None
    contact: Contact | None = None
    defaultPrice: PriceText
    defaultCapacity: Capacity
    defaultDurationMinutes: DurationMinutes
    maxSeatsPerBooking: MaxSeatsPerBooking
    options: OptionsList | None = None
    optionsSelectMode: OptionsSelectMode | None = None
    photoUrl: URL | None = None


class CreateServicePhotoUploadInput(BaseModel):
    contentType: ImageContentType
    size: ServicePhotoUploadSize


class CreateTimeSlotInput(BaseModel):
    serviceId: ServiceID
    startsAt: SlotStartsAt
    durationMinutes: DurationMinutes
    capacity: Capacity
    price: PriceText | None = None


class DeletedServiceEnvelope(BaseModel):
    id: ServiceID


class DeletedSlotEnvelope(BaseModel):
    id: UUIDModel


class GuestTicketResponse(BaseModel):
    ticket: AuthTicket
    messenger: Messenger
    messengerId: MessengerID
    displayName: str


class InvalidBody(BaseModel):
    error: str
    details: ValidationErrors


class LoginLinkPayload(BaseModel):
    organizerId: UUIDModel
    next: Annotated[str, Field(pattern='^\\/.*')]


class OrganizerProfile(BaseModel):
    id: UUIDModel
    slug: SlugShape
    name: DisplayName
    messenger: Messenger
    messengerId: str
    timezone: Timezone
    description: str | None
    photoUrl: str | None
    location: str | None
    contact: str | None
    language: AppLocale
    createdAt: str
    isDemo: bool


class PublicOrganizer(BaseModel):
    id: UUIDModel
    slug: SlugShape
    name: DisplayName
    timezone: Timezone
    description: str | None
    photoUrl: str | None
    location: str | None
    contact: str | None
    isDemo: bool


class RegisteredOrganizer(BaseModel):
    id: UUIDModel
    slug: SlugShape


class ServiceRecord(BaseModel):
    id: ServiceID
    organizerId: UUIDModel
    title: DisplayName
    description: str | None
    photoUrl: str | None
    location: str | None
    contact: str | None
    defaultPrice: PriceText
    defaultCapacity: Capacity
    defaultDurationMinutes: DurationMinutes
    maxSeatsPerBooking: MaxSeatsPerBooking
    options: list[str] | None
    optionsSelectMode: OptionsSelectMode | None
    createdAt: str


class ServicesEnvelope(BaseModel):
    services: list[ServiceRecord]


class Slug(RootModel[SlugShape]):
    root: SlugShape


class TelegramWidgetPayload(BaseModel):
    id: TelegramUserID
    first_name: TelegramName
    last_name: TelegramOptionalName | None = None
    username: TelegramOptionalName | None = None
    photo_url: URL | None = None
    auth_date: TelegramAuthDate
    hash: TelegramHash


class TimeSlotRecord(BaseModel):
    id: UUIDModel
    serviceId: ServiceID
    startsAt: str
    durationMinutes: DurationMinutes
    capacity: Capacity
    bookedCount: Annotated[int, Field(ge=0, le=9007199254740991)]
    price: str | None
    createdAt: str


class UpdateOrganizerProfileInput(BaseModel):
    name: DisplayName | None = None
    slug: Slug | None = None
    timezone: Timezone | None = None
    description: OrganizerDescription | None = None
    location: Location | None = None
    contact: Contact | None = None
    photoUrl: URL | None = None


class BookingEnvelope(BaseModel):
    booking: BookingRecord


class GuestBooking(BaseModel):
    id: UUIDModel
    status: BookingStatus
    seats: Seats
    guestName: DisplayName
    selectedOptions: list[str] | None
    createdAt: str
    manageToken: ManageToken
    canCancel: bool
    slot: TimeSlotRecord
    service: ServiceRecord
    organizer: PublicOrganizer


class GuestBookingEnvelope(BaseModel):
    booking: GuestBooking


class GuestBookingsEnvelope(BaseModel):
    bookings: list[GuestBooking]


class OrganizerEnvelope(BaseModel):
    organizer: OrganizerProfile


class RegisterOrganizerInput(BaseModel):
    ticket: AuthTicket
    slug: Slug
    name: DisplayName
    timezone: Timezone
    contact: Contact | None = None
    language: Annotated[AppLocale, Field(validate_default=True)] = 'en'


class Registered(BaseModel):
    organizer: RegisteredOrganizer


class ServiceEnvelope(BaseModel):
    service: ServiceRecord


class SlotEnvelope(BaseModel):
    slot: TimeSlotRecord


class SlotsEnvelope(BaseModel):
    slots: list[TimeSlotRecord]
