/**
 * Demo organizer seed data (ADR-010).
 *
 * Originally ported from `apps/web/lib/mock-data.ts` (deleted 2026-08-02) so the
 * public example page is backed by real rows and exercises the same queries as
 * any other organizer. This is now the **only** copy of the sample content.
 *
 * Two rules keep this seed usable long-term:
 *
 * 1. **Deterministic ids.** Re-seeding replaces rows in place instead of
 *    accumulating duplicates, and demo links stay stable.
 * 2. **Slot times relative to seed time**, never absolute. The old mock pinned
 *    `DEMO_NOW` to a fixed date, so every demo slot silently drifted into the
 *    past. Offsets are resolved against `now` at seed/refresh time instead.
 */

import { DEMO_ORGANIZER_ID, DEMO_ORGANIZER_SLUG, DEMO_SERVICE_IDS } from '@repo/contracts'

/** Deterministic demo slot ids (uuid — `time_slots.id` is a uuid column). */
const DEMO_SLOT_IDS = {
  // Upcoming yoga slots.
  y1: '01930000-0000-7000-8000-0000000a0001',
  y2: '01930000-0000-7000-8000-0000000a0002',
  y3: '01930000-0000-7000-8000-0000000a0003',
  y4: '01930000-0000-7000-8000-0000000a0004',
  // Past yoga slots (history for analytics).
  y5: '01930000-0000-7000-8000-0000000a0005',
  y6: '01930000-0000-7000-8000-0000000a0006',
  y7: '01930000-0000-7000-8000-0000000a0007',
  y8: '01930000-0000-7000-8000-0000000a0008',
  // Upcoming pottery slots.
  p1: '01930000-0000-7000-8000-0000000b0001',
  p2: '01930000-0000-7000-8000-0000000b0002',
  p3: '01930000-0000-7000-8000-0000000b0003',
  // Past pottery slots.
  p4: '01930000-0000-7000-8000-0000000b0004',
  p5: '01930000-0000-7000-8000-0000000b0005',
  // Upcoming breathwork slots.
  b1: '01930000-0000-7000-8000-0000000c0001',
  b2: '01930000-0000-7000-8000-0000000c0002',
  b3: '01930000-0000-7000-8000-0000000c0003',
  // Past breathwork slots.
  b4: '01930000-0000-7000-8000-0000000c0004',
  b5: '01930000-0000-7000-8000-0000000c0005',
  b6: '01930000-0000-7000-8000-0000000c0006',
} as const

/** Deterministic demo booking ids. */
const DEMO_BOOKING_IDS = {
  b1: '01930000-0000-7000-8000-0000000d0001',
  b2: '01930000-0000-7000-8000-0000000d0002',
  b3: '01930000-0000-7000-8000-0000000d0003',
  b4: '01930000-0000-7000-8000-0000000d0004',
  b5: '01930000-0000-7000-8000-0000000d0005',
  b6: '01930000-0000-7000-8000-0000000d0006',
  b7: '01930000-0000-7000-8000-0000000d0007',
  b8: '01930000-0000-7000-8000-0000000d0008',
  b9: '01930000-0000-7000-8000-0000000d0009',
  b10: '01930000-0000-7000-8000-0000000d000a',
  b11: '01930000-0000-7000-8000-0000000d000b',
  b12: '01930000-0000-7000-8000-0000000d000c',
  b13: '01930000-0000-7000-8000-0000000d000d',
  b14: '01930000-0000-7000-8000-0000000d000e',
  b15: '01930000-0000-7000-8000-0000000d000f',
  b16: '01930000-0000-7000-8000-0000000d0010',
  b17: '01930000-0000-7000-8000-0000000d0011',
  b18: '01930000-0000-7000-8000-0000000d0012',
  b19: '01930000-0000-7000-8000-0000000d0013',
  b20: '01930000-0000-7000-8000-0000000d0014',
  b21: '01930000-0000-7000-8000-0000000d0015',
  b22: '01930000-0000-7000-8000-0000000d0016',
  b23: '01930000-0000-7000-8000-0000000d0017',
  b24: '01930000-0000-7000-8000-0000000d0018',
  b25: '01930000-0000-7000-8000-0000000d0019',
  b26: '01930000-0000-7000-8000-0000000d001a',
  b27: '01930000-0000-7000-8000-0000000d001b',
  b28: '01930000-0000-7000-8000-0000000d001c',
  b29: '01930000-0000-7000-8000-0000000d001d',
  b30: '01930000-0000-7000-8000-0000000d001e',
  b31: '01930000-0000-7000-8000-0000000d001f',
  b32: '01930000-0000-7000-8000-0000000d0020',
  b33: '01930000-0000-7000-8000-0000000d0021',
  b34: '01930000-0000-7000-8000-0000000d0022',
  b35: '01930000-0000-7000-8000-0000000d0023',
  b36: '01930000-0000-7000-8000-0000000d0024',
  b37: '01930000-0000-7000-8000-0000000d0025',
  b38: '01930000-0000-7000-8000-0000000d0026',
  b39: '01930000-0000-7000-8000-0000000d0027',
  b40: '01930000-0000-7000-8000-0000000d0028',
} as const

export const DEMO_TIMEZONE = 'Europe/Belgrade'

export const demoOrganizer = {
  id: DEMO_ORGANIZER_ID,
  slug: DEMO_ORGANIZER_SLUG,
  name: 'Studio Demo',
  messenger: 'telegram' as const,
  /**
   * Sentinel messenger id — deliberately not a real Telegram account, so the
   * demo can never be logged into via the widget and the worker has nobody to
   * notify. Must stay unique against `organizers_messenger_id_key`.
   */
  messengerId: 'demo-account',
  timezone: DEMO_TIMEZONE,
  description: `**Boutique movement studio** in the heart of Belgrade.

Small-group **yoga**, **breathwork**, and **pottery** — come as you are, _beginners always welcome_.

What we offer:

- 🧘 Morning Vinyasa flow
- 🌬️ Evening breathwork circles
- 🏺 Hand-building pottery workshops

_This is a read-only demo page — [create your own](https://countmein.group/signup) in minutes._`,
  photoUrl: '/organizer-avatar.png',
  location: 'Kralja Petra 123, Belgrade',
  contact: 'studio@studiodemo.rs',
}

export const demoServices = [
  {
    id: DEMO_SERVICE_IDS.yoga,
    organizerId: DEMO_ORGANIZER_ID,
    title: 'Morning Vinyasa Flow',
    description:
      'A dynamic 60-minute flow to wake up the body and mind. Suitable for all levels. Mats and props provided.',
    photoUrl: '/service-yoga.png',
    location: null,
    contact: null,
    defaultPrice: '1200 RSD',
    defaultCapacity: 12,
    defaultDurationMinutes: 60,
    maxSeatsPerBooking: 2,
    options: ['Downtown studio', 'Riverside studio'],
    optionsSelectMode: 'single' as const,
  },
  {
    id: DEMO_SERVICE_IDS.pottery,
    organizerId: DEMO_ORGANIZER_ID,
    title: 'Hand-Building Pottery Workshop',
    description:
      'Shape your own mug or bowl from scratch. All clay, tools, and firing included. Great for a creative afternoon with friends.',
    photoUrl: '/service-pottery.png',
    location: 'Ceramics Loft, Cetinjska 15, Belgrade',
    contact: '+381 64 999 1234',
    defaultPrice: 'from 2500 RSD',
    defaultCapacity: 8,
    defaultDurationMinutes: 120,
    maxSeatsPerBooking: 4,
    options: ['Bring a friend (+1 seat)', 'Take-home glaze kit', 'Photo of your piece'],
    optionsSelectMode: 'multi' as const,
  },
  {
    id: DEMO_SERVICE_IDS.breathwork,
    organizerId: DEMO_ORGANIZER_ID,
    title: 'Evening Breathwork Circle',
    description:
      'A calming 45-minute guided breathwork session to close out your day. Dim lights, warm blankets, deep rest.',
    photoUrl: '/service-breathwork.png',
    location: null,
    contact: null,
    defaultPrice: '900 RSD',
    defaultCapacity: 16,
    defaultDurationMinutes: 45,
    maxSeatsPerBooking: 1,
    options: null,
    optionsSelectMode: null,
  },
]

/**
 * Slot templates: `dayOffset` / `hour` are resolved against the day *after* the
 * seed run, so a refresh always produces a week of strictly upcoming slots.
 *
 * Anchoring on "tomorrow" rather than "today" matters: a `dayOffset: 0` slot at
 * 07:00 would already be in the past whenever the seed runs later in the day,
 * and a demo page whose first slot is expired is exactly the failure this seed
 * exists to fix.
 *
 * Negative `dayOffset` values produce **past** slots — the history analytics
 * needs. They are excluded from the public "upcoming" list automatically
 * (`listUpcomingSlotsForServices` filters on `startsAt >= now`), but they keep
 * their bookings so the cabinet's bookings table and analytics have a past.
 */
const demoSlotTemplates = [
  // Yoga — a mix of open, filling and full so the UI shows every seat state.
  {
    id: DEMO_SLOT_IDS.y1,
    serviceId: DEMO_SERVICE_IDS.yoga,
    dayOffset: 0,
    hour: 7,
    durationMinutes: 60,
    capacity: 12,
    bookedCount: 9,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.y2,
    serviceId: DEMO_SERVICE_IDS.yoga,
    dayOffset: 1,
    hour: 7,
    durationMinutes: 60,
    capacity: 12,
    bookedCount: 12,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.y3,
    serviceId: DEMO_SERVICE_IDS.yoga,
    dayOffset: 2,
    hour: 7,
    durationMinutes: 60,
    capacity: 12,
    bookedCount: 4,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.y4,
    serviceId: DEMO_SERVICE_IDS.yoga,
    dayOffset: 3,
    hour: 7,
    durationMinutes: 60,
    capacity: 12,
    bookedCount: 1,
    price: '1400 RSD',
  },
  // Past yoga slots (history).
  {
    id: DEMO_SLOT_IDS.y5,
    serviceId: DEMO_SERVICE_IDS.yoga,
    dayOffset: -3,
    hour: 7,
    durationMinutes: 60,
    capacity: 12,
    bookedCount: 12,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.y6,
    serviceId: DEMO_SERVICE_IDS.yoga,
    dayOffset: -10,
    hour: 7,
    durationMinutes: 60,
    capacity: 12,
    bookedCount: 10,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.y7,
    serviceId: DEMO_SERVICE_IDS.yoga,
    dayOffset: -17,
    hour: 7,
    durationMinutes: 60,
    capacity: 12,
    bookedCount: 8,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.y8,
    serviceId: DEMO_SERVICE_IDS.yoga,
    dayOffset: -24,
    hour: 7,
    durationMinutes: 60,
    capacity: 12,
    bookedCount: 11,
    price: null,
  },
  // Pottery
  {
    id: DEMO_SLOT_IDS.p1,
    serviceId: DEMO_SERVICE_IDS.pottery,
    dayOffset: 1,
    hour: 15,
    durationMinutes: 120,
    capacity: 8,
    bookedCount: 5,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.p2,
    serviceId: DEMO_SERVICE_IDS.pottery,
    dayOffset: 4,
    hour: 15,
    durationMinutes: 120,
    capacity: 8,
    bookedCount: 8,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.p3,
    serviceId: DEMO_SERVICE_IDS.pottery,
    dayOffset: 6,
    hour: 11,
    durationMinutes: 120,
    capacity: 8,
    bookedCount: 2,
    price: null,
  },
  // Past pottery slots.
  {
    id: DEMO_SLOT_IDS.p4,
    serviceId: DEMO_SERVICE_IDS.pottery,
    dayOffset: -5,
    hour: 15,
    durationMinutes: 120,
    capacity: 8,
    bookedCount: 8,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.p5,
    serviceId: DEMO_SERVICE_IDS.pottery,
    dayOffset: -19,
    hour: 11,
    durationMinutes: 120,
    capacity: 8,
    bookedCount: 6,
    price: null,
  },
  // Breathwork
  {
    id: DEMO_SLOT_IDS.b1,
    serviceId: DEMO_SERVICE_IDS.breathwork,
    dayOffset: 0,
    hour: 18,
    durationMinutes: 45,
    capacity: 16,
    bookedCount: 11,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.b2,
    serviceId: DEMO_SERVICE_IDS.breathwork,
    dayOffset: 2,
    hour: 18,
    durationMinutes: 45,
    capacity: 16,
    bookedCount: 16,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.b3,
    serviceId: DEMO_SERVICE_IDS.breathwork,
    dayOffset: 5,
    hour: 18,
    durationMinutes: 45,
    capacity: 16,
    bookedCount: 6,
    price: null,
  },
  // Past breathwork slots.
  {
    id: DEMO_SLOT_IDS.b4,
    serviceId: DEMO_SERVICE_IDS.breathwork,
    dayOffset: -2,
    hour: 18,
    durationMinutes: 45,
    capacity: 16,
    bookedCount: 16,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.b5,
    serviceId: DEMO_SERVICE_IDS.breathwork,
    dayOffset: -9,
    hour: 18,
    durationMinutes: 45,
    capacity: 16,
    bookedCount: 14,
    price: null,
  },
  {
    id: DEMO_SLOT_IDS.b6,
    serviceId: DEMO_SERVICE_IDS.breathwork,
    dayOffset: -16,
    hour: 18,
    durationMinutes: 45,
    capacity: 16,
    bookedCount: 13,
    price: null,
  },
]

/**
 * Resolve slot templates against `now`.
 * `bookedCount` is seeded as a plain number rather than derived from the
 * `bookings` rows below: the demo intentionally shows realistic fill levels
 * without needing a booking row per seat. Because the account is read-only,
 * these counters never drift.
 */
export function buildDemoSlots(now: Date = new Date()) {
  return demoSlotTemplates.map((template) => {
    const startsAt = new Date(now)
    startsAt.setUTCDate(startsAt.getUTCDate() + template.dayOffset + 1)
    startsAt.setUTCHours(template.hour, 0, 0, 0)

    return {
      id: template.id,
      serviceId: template.serviceId,
      startsAt,
      durationMinutes: template.durationMinutes,
      capacity: template.capacity,
      bookedCount: template.bookedCount,
      price: template.price,
    }
  })
}

/**
 * Illustrative bookings for the cabinet's bookings table and analytics.
 * `manageToken`s are deterministic and publicly known — acceptable only because
 * every write path rejects the demo account (ADR-010), so a leaked demo token
 * cannot cancel anything.
 *
 * Spread across the last ~25 days so the 30-day analytics window and the 7-day
 * trend chart have real data. Each guest books a given slot at most once
 * (confirmed), honouring the `bookings_one_active_per_guest_per_slot` partial
 * unique index.
 */
export function buildDemoBookings(now: Date = new Date()) {
  const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000)

  return [
    // ── Recent (last 7 days) — drives the trend chart. ──────────────────────
    {
      id: DEMO_BOOKING_IDS.b1,
      timeSlotId: DEMO_SLOT_IDS.y1,
      status: 'confirmed' as const,
      seats: 2,
      guestName: 'Mila Petrović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-1',
      guestMessengerLogin: '@milapetrovic',
      manageToken: 'demo-manage-token-1',
      selectedOptions: ['Downtown studio'],
      createdAt: daysAgo(2),
    },
    {
      id: DEMO_BOOKING_IDS.b2,
      timeSlotId: DEMO_SLOT_IDS.p1,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Noah Ellis',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-2',
      guestMessengerLogin: null,
      manageToken: 'demo-manage-token-2',
      selectedOptions: ['Take-home glaze kit', 'Photo of your piece'],
      createdAt: daysAgo(3),
    },
    {
      id: DEMO_BOOKING_IDS.b3,
      timeSlotId: DEMO_SLOT_IDS.b1,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Ana Kovač',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-3',
      guestMessengerLogin: '@ana_kovac',
      manageToken: 'demo-manage-token-3',
      selectedOptions: null,
      createdAt: daysAgo(1),
    },
    {
      id: DEMO_BOOKING_IDS.b4,
      timeSlotId: DEMO_SLOT_IDS.y3,
      status: 'confirmed' as const,
      seats: 3,
      guestName: 'Luka Jovanović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-4',
      guestMessengerLogin: '@lukajovanovic',
      manageToken: 'demo-manage-token-4',
      selectedOptions: ['Riverside studio'],
      createdAt: daysAgo(1),
    },
    {
      id: DEMO_BOOKING_IDS.b5,
      timeSlotId: DEMO_SLOT_IDS.p1,
      status: 'cancelled' as const,
      seats: 1,
      guestName: 'Sara Nikolić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-5',
      guestMessengerLogin: '@sara_nikolic',
      manageToken: 'demo-manage-token-5',
      selectedOptions: null,
      createdAt: daysAgo(4),
    },
    {
      id: DEMO_BOOKING_IDS.b6,
      timeSlotId: DEMO_SLOT_IDS.b2,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Elena Marković',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-6',
      guestMessengerLogin: '@elenamarkovic',
      manageToken: 'demo-manage-token-6',
      selectedOptions: null,
      createdAt: daysAgo(5),
    },
    {
      id: DEMO_BOOKING_IDS.b7,
      timeSlotId: DEMO_SLOT_IDS.b2,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Filip Stanković',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-7',
      guestMessengerLogin: '@filips',
      manageToken: 'demo-manage-token-7',
      selectedOptions: null,
      createdAt: daysAgo(6),
    },
    {
      id: DEMO_BOOKING_IDS.b8,
      timeSlotId: DEMO_SLOT_IDS.y2,
      status: 'confirmed' as const,
      seats: 2,
      guestName: 'Jelena Popović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-8',
      guestMessengerLogin: '@jelenap',
      manageToken: 'demo-manage-token-8',
      selectedOptions: ['Downtown studio'],
      createdAt: daysAgo(6),
    },
    // ── 8–30 days ago — fills the 30-day window and the previous window. ─────
    {
      id: DEMO_BOOKING_IDS.b9,
      timeSlotId: DEMO_SLOT_IDS.y5,
      status: 'confirmed' as const,
      seats: 2,
      guestName: 'Marko Đorđević',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-9',
      guestMessengerLogin: '@markod',
      manageToken: 'demo-manage-token-9',
      selectedOptions: ['Riverside studio'],
      createdAt: daysAgo(8),
    },
    {
      id: DEMO_BOOKING_IDS.b10,
      timeSlotId: DEMO_SLOT_IDS.b4,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Tijana Radosavljević',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-10',
      guestMessengerLogin: '@tijanar',
      manageToken: 'demo-manage-token-10',
      selectedOptions: null,
      createdAt: daysAgo(9),
    },
    {
      id: DEMO_BOOKING_IDS.b11,
      timeSlotId: DEMO_SLOT_IDS.p4,
      status: 'confirmed' as const,
      seats: 2,
      guestName: 'Andrej Simić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-11',
      guestMessengerLogin: '@andrejs',
      manageToken: 'demo-manage-token-11',
      selectedOptions: ['Bring a friend (+1 seat)'],
      createdAt: daysAgo(10),
    },
    {
      id: DEMO_BOOKING_IDS.b12,
      timeSlotId: DEMO_SLOT_IDS.y6,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Katarina Lukić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-12',
      guestMessengerLogin: '@katarinal',
      manageToken: 'demo-manage-token-12',
      selectedOptions: ['Downtown studio'],
      createdAt: daysAgo(12),
    },
    {
      id: DEMO_BOOKING_IDS.b13,
      timeSlotId: DEMO_SLOT_IDS.b5,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Nikola Vuković',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-13',
      guestMessengerLogin: '@nikolav',
      manageToken: 'demo-manage-token-13',
      selectedOptions: null,
      createdAt: daysAgo(13),
    },
    {
      id: DEMO_BOOKING_IDS.b14,
      timeSlotId: DEMO_SLOT_IDS.y5,
      status: 'cancelled' as const,
      seats: 1,
      guestName: 'Petra Janković',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-14',
      guestMessengerLogin: '@petraj',
      manageToken: 'demo-manage-token-14',
      selectedOptions: ['Downtown studio'],
      createdAt: daysAgo(14),
    },
    {
      id: DEMO_BOOKING_IDS.b15,
      timeSlotId: DEMO_SLOT_IDS.p4,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Stefan Antić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-15',
      guestMessengerLogin: '@stefana',
      manageToken: 'demo-manage-token-15',
      selectedOptions: ['Photo of your piece'],
      createdAt: daysAgo(15),
    },
    {
      id: DEMO_BOOKING_IDS.b16,
      timeSlotId: DEMO_SLOT_IDS.y6,
      status: 'confirmed' as const,
      seats: 2,
      guestName: 'Olga Branković',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-16',
      guestMessengerLogin: '@olgab',
      manageToken: 'demo-manage-token-16',
      selectedOptions: ['Riverside studio'],
      createdAt: daysAgo(16),
    },
    {
      id: DEMO_BOOKING_IDS.b17,
      timeSlotId: DEMO_SLOT_IDS.b5,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Dušan Pavlović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-17',
      guestMessengerLogin: '@dusanp',
      manageToken: 'demo-manage-token-17',
      selectedOptions: null,
      createdAt: daysAgo(17),
    },
    {
      id: DEMO_BOOKING_IDS.b18,
      timeSlotId: DEMO_SLOT_IDS.y7,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Maja Ilić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-18',
      guestMessengerLogin: '@majailic',
      manageToken: 'demo-manage-token-18',
      selectedOptions: ['Downtown studio'],
      createdAt: daysAgo(18),
    },
    {
      id: DEMO_BOOKING_IDS.b19,
      timeSlotId: DEMO_SLOT_IDS.p5,
      status: 'confirmed' as const,
      seats: 2,
      guestName: 'Bogdan Zarić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-19',
      guestMessengerLogin: '@bogdanz',
      manageToken: 'demo-manage-token-19',
      selectedOptions: ['Bring a friend (+1 seat)', 'Take-home glaze kit'],
      createdAt: daysAgo(19),
    },
    {
      id: DEMO_BOOKING_IDS.b20,
      timeSlotId: DEMO_SLOT_IDS.b6,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Tamara Cvetković',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-20',
      guestMessengerLogin: '@tamarac',
      manageToken: 'demo-manage-token-20',
      selectedOptions: null,
      createdAt: daysAgo(20),
    },
    {
      id: DEMO_BOOKING_IDS.b21,
      timeSlotId: DEMO_SLOT_IDS.y7,
      status: 'confirmed' as const,
      seats: 2,
      guestName: 'Vladimir Nikolić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-21',
      guestMessengerLogin: '@vladimirn',
      manageToken: 'demo-manage-token-21',
      selectedOptions: ['Riverside studio'],
      createdAt: daysAgo(21),
    },
    {
      id: DEMO_BOOKING_IDS.b22,
      timeSlotId: DEMO_SLOT_IDS.p5,
      status: 'cancelled' as const,
      seats: 1,
      guestName: 'Isidora Milovanović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-22',
      guestMessengerLogin: '@isidoram',
      manageToken: 'demo-manage-token-22',
      selectedOptions: null,
      createdAt: daysAgo(22),
    },
    {
      id: DEMO_BOOKING_IDS.b23,
      timeSlotId: DEMO_SLOT_IDS.y8,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Aleksandar Tomić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-23',
      guestMessengerLogin: '@aleksandart',
      manageToken: 'demo-manage-token-23',
      selectedOptions: ['Downtown studio'],
      createdAt: daysAgo(23),
    },
    {
      id: DEMO_BOOKING_IDS.b24,
      timeSlotId: DEMO_SLOT_IDS.b6,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Natalija Pavlović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-24',
      guestMessengerLogin: '@natalijap',
      manageToken: 'demo-manage-token-24',
      selectedOptions: null,
      createdAt: daysAgo(24),
    },
    {
      id: DEMO_BOOKING_IDS.b25,
      timeSlotId: DEMO_SLOT_IDS.y8,
      status: 'confirmed' as const,
      seats: 2,
      guestName: 'Goran Stevanović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-25',
      guestMessengerLogin: '@gorans',
      manageToken: 'demo-manage-token-25',
      selectedOptions: ['Riverside studio'],
      createdAt: daysAgo(25),
    },
    // ── 31–60 days ago — the previous 30-day window for the delta metric. ────
    {
      id: DEMO_BOOKING_IDS.b26,
      timeSlotId: DEMO_SLOT_IDS.y8,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Milica Radović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-26',
      guestMessengerLogin: '@milicar',
      manageToken: 'demo-manage-token-26',
      selectedOptions: ['Downtown studio'],
      createdAt: daysAgo(32),
    },
    {
      id: DEMO_BOOKING_IDS.b27,
      timeSlotId: DEMO_SLOT_IDS.b6,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Radovan Knežević',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-27',
      guestMessengerLogin: '@radovank',
      manageToken: 'demo-manage-token-27',
      selectedOptions: null,
      createdAt: daysAgo(34),
    },
    {
      id: DEMO_BOOKING_IDS.b28,
      timeSlotId: DEMO_SLOT_IDS.p5,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Sofija Marić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-28',
      guestMessengerLogin: '@sofijam',
      manageToken: 'demo-manage-token-28',
      selectedOptions: ['Take-home glaze kit'],
      createdAt: daysAgo(36),
    },
    {
      id: DEMO_BOOKING_IDS.b29,
      timeSlotId: DEMO_SLOT_IDS.y7,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Todor Jovanović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-29',
      guestMessengerLogin: '@todorj',
      manageToken: 'demo-manage-token-29',
      selectedOptions: ['Downtown studio'],
      createdAt: daysAgo(38),
    },
    {
      id: DEMO_BOOKING_IDS.b30,
      timeSlotId: DEMO_SLOT_IDS.b5,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Anastasija Milošević',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-30',
      guestMessengerLogin: '@anastasijam',
      manageToken: 'demo-manage-token-30',
      selectedOptions: null,
      createdAt: daysAgo(40),
    },
    {
      id: DEMO_BOOKING_IDS.b31,
      timeSlotId: DEMO_SLOT_IDS.y6,
      status: 'confirmed' as const,
      seats: 2,
      guestName: 'Lazar Gagić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-31',
      guestMessengerLogin: '@lazarg',
      manageToken: 'demo-manage-token-31',
      selectedOptions: ['Riverside studio'],
      createdAt: daysAgo(42),
    },
    {
      id: DEMO_BOOKING_IDS.b32,
      timeSlotId: DEMO_SLOT_IDS.p4,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Vesna Protić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-32',
      guestMessengerLogin: '@vesnap',
      manageToken: 'demo-manage-token-32',
      selectedOptions: ['Photo of your piece'],
      createdAt: daysAgo(44),
    },
    {
      id: DEMO_BOOKING_IDS.b33,
      timeSlotId: DEMO_SLOT_IDS.b4,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Bojan Janković',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-33',
      guestMessengerLogin: '@bojanj',
      manageToken: 'demo-manage-token-33',
      selectedOptions: null,
      createdAt: daysAgo(46),
    },
    {
      id: DEMO_BOOKING_IDS.b34,
      timeSlotId: DEMO_SLOT_IDS.y5,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Ivana Dragović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-34',
      guestMessengerLogin: '@ivanad',
      manageToken: 'demo-manage-token-34',
      selectedOptions: ['Downtown studio'],
      createdAt: daysAgo(48),
    },
    {
      id: DEMO_BOOKING_IDS.b35,
      timeSlotId: DEMO_SLOT_IDS.b6,
      status: 'cancelled' as const,
      seats: 1,
      guestName: 'Miloš Arsić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-35',
      guestMessengerLogin: '@milosa',
      manageToken: 'demo-manage-token-35',
      selectedOptions: null,
      createdAt: daysAgo(50),
    },
    {
      id: DEMO_BOOKING_IDS.b36,
      timeSlotId: DEMO_SLOT_IDS.p5,
      status: 'confirmed' as const,
      seats: 2,
      guestName: 'Jelena Cvetanović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-36',
      guestMessengerLogin: '@jelenac',
      manageToken: 'demo-manage-token-36',
      selectedOptions: ['Bring a friend (+1 seat)'],
      createdAt: daysAgo(52),
    },
    {
      id: DEMO_BOOKING_IDS.b37,
      timeSlotId: DEMO_SLOT_IDS.y8,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Nemanja Kostić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-37',
      guestMessengerLogin: '@nemanjak',
      manageToken: 'demo-manage-token-37',
      selectedOptions: ['Riverside studio'],
      createdAt: daysAgo(54),
    },
    {
      id: DEMO_BOOKING_IDS.b38,
      timeSlotId: DEMO_SLOT_IDS.b4,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Milica Zorić',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-38',
      guestMessengerLogin: '@milicaz',
      manageToken: 'demo-manage-token-38',
      selectedOptions: null,
      createdAt: daysAgo(56),
    },
    {
      id: DEMO_BOOKING_IDS.b39,
      timeSlotId: DEMO_SLOT_IDS.y7,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Aleksa Mitrović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-39',
      guestMessengerLogin: '@aleksam',
      manageToken: 'demo-manage-token-39',
      selectedOptions: ['Downtown studio'],
      createdAt: daysAgo(58),
    },
    {
      id: DEMO_BOOKING_IDS.b40,
      timeSlotId: DEMO_SLOT_IDS.p4,
      status: 'confirmed' as const,
      seats: 1,
      guestName: 'Tamara Bogdanović',
      guestMessenger: 'telegram' as const,
      guestMessengerId: 'demo-guest-40',
      guestMessengerLogin: '@tamarab',
      manageToken: 'demo-manage-token-40',
      selectedOptions: ['Take-home glaze kit'],
      createdAt: daysAgo(60),
    },
  ]
}
